

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:340805022809:android:58aafb386adbec11b42d48",
        groups: "qa-team, trusted-testers",
        firebase_cli_token: "1//03Tmf2PeAkOzzCgYIARAAGAMSNwF-L9Ir3ABoymfORXJ02XdcDWJAJGBFFuu1Rs5JydOKpYhob5cpda9SFrjm3FqiAySp-gm02SU",
        android_artifact_type: "APK",
        upload_timeout: 500,
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "moazayman128@gmail.com",
        release_notes: "First Fastlane Firebase App Distribution Release"

  )
  end
end
